### ISSUE TITLE
rspell won't work if installed globally with pnpm

### ISSUE THREAD

**Issue by guilherssousa** [Lioness100/rspell#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

If you install the package using `pnpm i -g rspell`, the project won't run correctly and will display this error:

```shell
Error: Cannot find module '../node_modules/cspell/dist/util/fileHelper'
Require stack:
- C:\Users\<user>\AppData\Local\pnpm\global\5\.pnpm\rspell@1.6.2-1\node_modules\rspell\dist\cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\<user>\AppData\Local\pnpm\global\5\.pnpm\rspell@1.6.2-1\node_modules\rspell\dist\cli.js:2:604)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\<user>\\AppData\\Local\\pnpm\\global\\5\\.pnpm\\rspell@1.6.2-1\\node_modules\\rspell\\dist\\cli.js'
  ]
}
```

### Steps To Reproduce

Run `pnpm i -g rspell` on your shell.

### Additional context

This is probably thanks to pnpm caching design where `cspell` package isn't exposed to the actual project, instead using symlinks to pnpm's virtual store.

**Comment by Lioness100** [comment]
Hi, thanks for making an issue! This issue is from the following line:
https://github.com/Lioness100/rspell/blob/57d1050d8d4d22d74babda19c3aacbbfb3a03b29/src/config.ts#LL5

`cspell/util/fileHelper` is not a file exported from `cspell`. The only [exported patterns](https://nodejs.org/api/packages.html#main-entry-point-export) are:
https://github.com/streetsidesoftware/cspell/blob/8fd127d46c0a81b1625e20da344927d399ef36f2/packages/cspell/package.json#L11-L19

This can be ignored when using absolute or relative paths to import the file, which is what I did. However, as you said, this doesn't work with `pnpm`'s design (and it probably also doesn't work for the compiled binaries, but I haven't tested them). The only other fixes I can think of are submitting a PR/issue to cspell to export this file (its maintainer is very active), or we could stop relying on `readConfig` (which would be a lot of work/code). 

I'll probably do the former, unless you have any better ideas?

**Comment by guilherssousa** [comment]
You mean just adding `cspell` as a direct dependency to the project and just importing? (sounds kinda dumb question, but I'm really slow to get these dependency-related problems thanks to this new pnpm caching thing)

**Comment by Lioness100** [comment]
`cspell` is already a dep, `cspell-lib` is a different package. `cspell` is the command line application, which I use because we're basically doing the same thing as the cspell CLI. However, where the cspell CLI just spits out the typos, rspell helps you go through them to fix them. `cspell-lib` is the "cspell library used for code driven spelling checking" (the low level stuff that does most of the logic).

**Comment by Lioness100** [comment]
Thank you so so so much!!
